package com.silyosbekov.maze.entity;

import com.silyosbekov.maze.core.Direction;
import java.util.Arrays;
import java.util.Collections;

/**
 * Represents a maze game object. The maze is represented as a 2D grid of cells.
 * Each cell has walls on all sides. The maze is generated by removing walls between cells.
 */
public class Maze {
    private final int width;
    private final int height;
    private final MazeCell[][] mazeGrid; // 2D array of cells

    public Maze(int width, int height) {
        this.width = width;
        this.height = height;
        this.mazeGrid = new MazeCell[width][height];
        initializeCells();
        generateMaze(0, 0);
    }

    /**
     * Get a cell at the specified coordinates
     * @param x x-coordinate
     * @param y y-coordinate
     * @return cell at the specified coordinates
     */
    public MazeCell getCell(int x, int y) {
        if (x >= 0 && x < width && y >= 0 && y < height) {
            return mazeGrid[x][y];
        }

        return null;
    }

    /**
     * Get the width of the maze
     */
    public int getWidth() {
        return width;
    }

    /**
     * Get the height of the maze
     */
    public int getHeight() {
        return height;
    }

    /**
     * Generate the maze recursively. It generates a maze by removing walls between cells randomly.
     * @param currentX current x-coordinate
     * @param currentY current y-coordinate
     */
    private void generateMaze(int currentX, int currentY) {
        var directions = Arrays.asList(Direction.values());
        Collections.shuffle(directions);

        for (var direction : directions) {
            var nextX = currentX; // Next cell x-coordinate
            var nextY = currentY; // Next cell y-coordinate

            // Calculate the next cell coordinates based on the current cell and the direction
            switch (direction) {
                case Direction.UP:
                    nextY -= 1;
                    break;
                case Direction.DOWN:
                    nextY += 1;
                    break;
                case Direction.RIGHT:
                    nextX += 1;
                    break;
                case Direction.LEFT:
                    nextX -= 1;
                    break;
            }

            // Check if the next cell is within the maze bounds and is an initial cell (all walls intact),
            // then remove the walls between the current cell and the next cell and recursively generate the maze from the next cell.
            if (nextX >= 0 &&
                nextX < width &&
                nextY >= 0 &&
                nextY < height &&
                mazeGrid[nextX][nextY].isInitial()
            )
            {
                mazeGrid[currentX][currentY].removeWall(direction);
                mazeGrid[nextX][nextY].removeOppositeWall(direction);
                generateMaze(nextX, nextY);
            }
        }
    }

    /**
     * Initialize maze cells with all sides walled.
     */
    private void initializeCells() {
        for (int x = 0; x < width; x++) {
            for (int y = 0; y < height; y++) {
                mazeGrid[x][y] = new MazeCell(x, y);
            }
        }
    }
}
